title: Melvin Even
url: ""
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "resume"
 - name: "Misc. projects"
   link: "random"

collections:
  conf:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name